const GENERATED_PATH_PATTERNS: RegExp[] = [
  /(^|\/)package-lock\.json$/i,
  /(^|\/)yarn\.lock$/i,
  /(^|\/)pnpm-lock\.yaml$/i,
  /(^|\/)bun\.lockb$/i,
  /(^|\/)npm-shrinkwrap\.json$/i,
  /(^|\/)composer\.lock$/i,
  /(^|\/)poetry\.lock$/i,
  /(^|\/)Cargo\.lock$/i,
  /(^|\/)go\.sum$/i,
  /(^|\/)dist\//i,
  /(^|\/)build\//i,
  /(^|\/)out\//i,
  /(^|\/)\.next\//i,
  /(^|\/)coverage\//i,
  /(^|\/)vendor\//i,
  /(^|\/)node_modules\//i,
  /\.min\.(js|css)$/i,
  /\.bundle\.js$/i,
  /\.generated\.(ts|js|tsx|jsx)$/i,
  /(^|\/)graphql-types?\.ts$/i,
  /(^|\/)schema\.gql$/i,
];

const GENERATED_HEADER_HINTS = [
  "this file is generated",
  "code generated by",
  "@generated",
  "do not edit this file",
  "autogenerated",
];

export function isGeneratedFile(path: string, patch?: string): boolean {
  if (GENERATED_PATH_PATTERNS.some((pattern) => pattern.test(path))) {
    return true;
  }
  if (!patch) {
    return false;
  }
  const sample = patch.slice(0, 2000).toLowerCase();
  return GENERATED_HEADER_HINTS.some((hint) => sample.includes(hint));
}

export function isLockfile(path: string): boolean {
  return /(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb|composer\.lock|poetry\.lock|Cargo\.lock|go\.sum)$/i.test(
    path,
  );
}

export function isTestFile(path: string): boolean {
  return (
    /(^|\/)(__tests__|tests?|spec)\//i.test(path) ||
    /\.(test|spec)\.(ts|tsx|js|jsx|mjs|cjs)$/i.test(path) ||
    /(^|\/)test_.*\.py$/i.test(path)
  );
}
